### ISSUE TITLE
no render progress ? 

### ISSUE THREAD

**Issue by swayways** [LilyStilson/AErender-Launcher#7]
**What happened?**
Rendering progress doesn't work, its either 0 or 100, but nothing in between. So its impossible to evaluate render time.
This test was done with multiple comps selected and multithreading enabled. Rendered out Quicktimes.
Thanks!
**To Reproduce**
1. *Action 1*
2. *Action 2*
...
4. *Error Appears*

**Expected behavior**

**Screenshots**

**Required information:**
***Software***
- AErender Launcher version: v0.8.2-beta
- Adobe After Effects version: AE2020
- OS: MAcOS 10.14.6

***Hardware***
- CPU: INtel Xeon E5 6 core 3.5 Ghz
- GPU: AMD FIrepro D500 3Go
- RAM: 64Go 1866 Mhz DDR3

**Additional context**
![Capture d’écran 2020-10-20 à 18 46 24](https://user-images.githubusercontent.com/66728110/96618282-097ec800-1305-11eb-88a0-45cabb5d187d.png)

**Comment by LilyStilson** [comment]
Update to  `v0.8.6-beta`, this will solve your problem. Displaying progress was very wonky in `v0.8.2-beta`, so you just should update to newer version where it was fixed.
