### ISSUE TITLE
render settings configurator?

### ISSUE THREAD

**Issue by swayways** [LilyStilson/AErender-Launcher#8]
**What exactly do you want us to add?**
Knowing that the aep project file is binary, I suppose carrying over Render Settings from the current project isn't possible. If so, could it be possible to have a Render Setting Configurator, just like the Output Module? such items worth configuring would be :
- proxy use
- bit depth
- field rendering
- skip existing files
Each comp in the project can potentially be rendered out differently; 

<b>*(Optional)* If possible attach some concept artworks of your feature</b>

**Describe alternatives you've considered**
the alternative would be to save separate projects per comp... ?
**Additional context**

**Comment by LilyStilson** [comment]
Implemented in `v0.8.9-beta`
